Repository KorrdsTech/Jeth, pull requests merged in 2022-05, with the labels that each got.

#81 Update Guild.js
  src/utils/database/collections/Guild.js
Labels: Priority: Low, Module: Jeth (Discord) 🎀

#85 Timestamp New
  src/commands/Mod/HistoryCommand.js
Labels: Type: Enhancement ✨, Module: Jeth (Discord) 🎀

#86 fix database issue
  src/utils/database/Collection.js
Labels: ‍‍Status: Needs Testing 💻, Priority: High, ‍‍✅ accepted

#89 Update VIPCommand.js
  src/commands/VIP/VIPCommand.js
Labels: Priority: Low, Module: Jeth (Discord) 🎀

#90 Update messageCreate.js
  src/listeners/messageCreate.js
Labels: ‍‍Status: Needs Testing 💻, Priority: Low, Module: Jeth (Discord) 🎀

#93 Update guildMemberRemove.js
  src/listeners/guildMemberRemove.js
Labels: Module: Jeth (Discord) 🎀

#94 Fix bug in guildMemberAdd
  src/utils/database/collections/Guild.js
Labels: Type: Bug 🐞, Priority: Medium, Module: Jeth (Discord) 🎀, ‍‍✅ accepted
