Repository KorrdsTech/Jeth, pull requests merged in 2022-01, with the labels that each got.

#30 🔐 Lock.js Fixed Closes #29
  commands/Moderation/chat.js
Labels: Type: Enhancement ✨, 🚀 performance, Bounty 🤑, ‍‍✅ accepted

#31 📸 guildBanAdd - Module Logs
  listeners/guildBanAdd.js
Labels: Type: Bug 🐞, ‍‍Status: Needs Testing 💻, 🔓 security, Priority: Critical, Module: Jeth (Discord) 🎀

#32 🔐 Correções Adicionais
  listeners/guildBanAdd.js
Labels: 🔓 security, Priority: High, 🚀 performance, Module: Jeth (Discord) 🎀, Bounty 🤑, ‍‍✅ accepted

#33 👨‍🔧 -Corrigindo block-word module
  listeners/message.js
Labels: Type: Enhancement ✨, ‍‍Status: Needs Testing 💻, 🔓 security, Priority: High, 🚀 performance, Module: Jeth (Discord) 🎀

#34 Update index.md
  docs/index.md
Labels: Type: Enhancement ✨, Status: On Hold 😴, 🔓 security, Priority: Critical, dependencies

#35 🏆Re-write README.md
  README.md
Labels: Type: Enhancement ✨, Priority: Low, 🚀 performance

#37 changing the project's license to a more suitable one
  LICENSE
Labels: Type: Enhancement ✨, 🔓 security, ‍‍✅ accepted

#36 Editing `listeners` because it became deprecated.
  listeners/guildMemberAdd.js
  listeners/message.js
Labels: Type: Enhancement ✨, 🔓 security, 🚀 performance, Module: Jeth (Discord) 🎀, ⏰ future

#39 Adding new counters and fixing issues
  utils/Command.js
  utils/TranslateFunctions.js
Labels: Type: Enhancement ✨, 🚀 performance, Module: Jeth (Discord) 🎀, Good First Issue 😊

#40 Switch of owner ID's because main account is disabled.
  listeners/message.js
  utils/Command.js
Labels: 🔓 security, Priority: High, Module: Jeth (Discord) 🎀, Good First Issue 😊, ‍‍✅ accepted

#43 Changes in security
  SECURITY.md
Labels: Type: Enhancement ✨, 🔓 security, Priority: Low

#41 Fixing major rebase erros #26 #27 #28 #29 #30 #31
  commands/Entretenimento/1v1.js
  commands/Moderação/anuncio.js
  commands/Moderação/ban.js
  commands/Moderação/chat.js
  commands/Moderação/raidban.js
  commands/Moderação/softban.js
  commands/Moderação/timeout.js
  commands/Moderação/unban.js
  commands/Moderação/warn.js
  commands/Moderação/welcomeModule.js
  commands/Registro/registros.js
  listeners/guildBanAdd.js
Labels: Type: Enhancement ✨, Type: Bug 🐞, Priority: Critical, 🚀 performance, Module: Jeth (Discord) 🎀, Help Wanted 💁, dependencies, Bounty 🤑, ‍‍✅ accepted

#42 quick fix #26 #27 #28 #29 #30 #31
  listeners/message.js
  listeners/messageDeleted.js
  utils/Command.js
Labels: Type: Enhancement ✨, Priority: Critical, 🚀 performance, Module: Jeth (Discord) 🎀, ✂ duplicate, dependencies, Bounty 🤑, ‍‍✅ accepted

#45 Editing owner ID into bug report
  commands/Miscellaneous/bug.js
Labels: Type: Enhancement ✨, 🔓 security, Priority: Low, 🚀 performance, Module: Jeth (Discord) 🎀, Good First Issue 😊, ‍‍✅ accepted

#49 Update README.md
  README.md
Labels: Type: Enhancement ✨, 🔓 security, Module: Jeth (Discord) 🎀

#50 Fixing bug's into error messages
  commands/Contador/contador.js
  commands/Miscellaneous/say.js
  commands/Miscellaneous/suggestion.js
  commands/Moderação/gifban.js
  commands/Moderação/saida.js
  commands/Moderação/slowmode.js
  commands/Moderação/welcomeModule.js
Labels: Type: Bug 🐞, Priority: Low, 🚀 performance, Module: Jeth (Discord) 🎀, Good First Issue 😊, ‍‍✅ accepted

#52 Adding new prohibited words
  listeners/message.js
Labels: Type: Enhancement ✨, 🔓 security, Priority: Medium, Module: Jeth (Discord) 🎀

#51 Fixing emoji bug
  commands/Somente Donos/relatorio.js
Labels: Type: Bug 🐞, Priority: Low, Module: Jeth (Discord) 🎀, Good First Issue 😊, Bounty 🤑, ‍‍✅ accepted

#53 Emoji fix
  listeners/message.js
Labels: Type: Enhancement ✨, Type: Bug 🐞, Priority: Low

#56 Command kill were changed into punching #55
  commands/Entretenimento/matar.js
Labels: Type: Enhancement ✨, Priority: Medium, Module: Jeth (Discord) 🎀, ✂ duplicate

#55 Command kill were changed into punching
  commands/Entretenimento/soco.js
Labels: Type: Enhancement ✨, ‍‍Status: Needs Testing 💻, Priority: Medium, 🚀 performance, Module: Jeth (Discord) 🎀
