Repository KorrdsTech/Jeth, pull requests merged in 2022-06, with the labels that each got.

#97 New System counter bans
  src/utils/database/collections/Bans.js
Labels: Type: Enhancement ✨, 🔓 security, Priority: Medium, Module: Jeth (Discord) 🎀, ‍‍✅ accepted

#98 Fix chat command
  src/commands/Mod/ChatCommand.js
Labels: Type: Enhancement ✨, Priority: High, Module: Jeth (Discord) 🎀, ‍‍✅ accepted

#99 Update messageCreate.js
  src/listeners/messageCreate.js
Labels: Type: Bug 🐞, Status: Won't Fix 🤷, ‍‍Status: Needs Testing 💻, Priority: High, Module: Jeth (Discord) 🎀

#101 Update VIPConfigCommand.js
  src/commands/VIP/VIPConfigCommand.js
Labels: Type: Enhancement ✨, Type: Bug 🐞, Priority: High, Module: Jeth (Discord) 🎀, ‍‍✅ accepted
